# Generated by Django 4.0.2 on 2022-02-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_flight_estimated_duration_flight_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_number', 'carrier')},
        ),
    ]
