# Generated by Django 4.0.2 on 2022-02-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_flight_options_alter_flight_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_number', 'departure_port')},
        ),
    ]
