# Generated by Django 4.0.2 on 2022-05-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_flight_departure_date_alter_flight_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
    ]
