# Generated by Django 3.2.13 on 2022-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
    ]
