version: "3"
services:
  recommendations:
    image: recommendations
    ports:
      - 8100:8100
    env_file:
      - .env
    networks:
      - backend

  allflights:
    image: allflights
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - recommendations
    networks:
      - backend

networks:
  backend:
