version: "3"
services:
  recommendations:
    image: 431869337998.dkr.ecr.us-east-1.amazonaws.com/recommendations
    container_name: recommendations
    ports:
      - 8100:8100
    env_file:
      - .env.prod
    networks:
      - backend

  allflights:
    image: 431869337998.dkr.ecr.us-east-1.amazonaws.com/allflights
    container_name: allflights
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - recommendations
    networks:
      - backend

networks:
  backend:
