version: 2.1

orbs:
  python: circleci/python@2.1.1
  eb: circleci/aws-elastic-beanstalk@1.0.0

workflows:
  main_workflow:
    jobs:
      - python/test
      - eb/deploy:
            context: aws-creds
            environment-name: allflightsapi-staging
            filters:
              branches:
                only:
                  - staging
            requires:
              - python/test
