version: 2.1

orbs:
  python: circleci/python@2.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1

workflows:
  main_workflow:
    jobs:
      - python/test
      - eb/deploy:
            environment-name: allflights-env
            application-name: allflights
            filters:
              branches:
                only:
                  - staging
            label: version-<<pipeline.number>>
            requires:
              - python/test
