# Generated by Django 4.0.2 on 2022-05-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_flight_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.DurationField(help_text='Estimated duration of flight', null=True),
        ),
    ]
