# Generated by Django 3.2.13 on 2022-05-22 16:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='fare',
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('class_name', models.CharField(choices=[('Economy', 'Economy'), ('Premium', 'Premium'), ('Business', 'Business')], default='Economy', max_length=10)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.flight')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='flight_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='app.flightclass'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_number', 'flight_class')},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='flight',
        ),
    ]
