# Generated by Django 3.2.13 on 2022-05-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220522_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='capacity',
        ),
        migrations.AddField(
            model_name='flight',
            name='business_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flight',
            name='premium_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
