# Generated by Django 3.2.13 on 2022-11-14 04:50

import app.models
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220526_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='seat',
            name='flight_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.flightclass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=app.models.path_and_filename, verbose_name='avatar'),
        ),
    ]
